// Single source of truth. PUBLIC-SAFE ONLY: employer generalized; no real FHI tokens.
export const LENSES = ['AI', 'ML', 'BI', 'IB'];

// Sources I connected into the warehouse (shown feeding in on the lineage graph).
export const sources = ['Shopify', 'Amazon', 'Amazon Vendor', 'Amazon Ads', 'TikTok Shop', 'TikTok Ads', 'Meta', 'Google Ads', 'GA4', 'GSC', 'GMC', 'SAP', 'ShipStation', 'Attentive', 'Euka'];

// Production projects that ran on the warehouse, grouped by business function (right side of the graph).
export const graphGroups = [
  { key: 'finance', label: 'the sale · finance', title: 'Financial analytics & decision support', ids: ['sell', 'fbt'],
    blurb: 'Warehouse-powered finance calls — a diligence reconciliation and a build-vs-buy decision.' },
  { key: 'growth', label: 'affiliate growth engine', title: 'Applied ML, LLM agents & automation — the affiliate growth engine', ids: ['discovery', 'engine', 'n8n'], chain: true,
    blurb: 'One end-to-end system, three parts: discovery finds & scores creators → the decision engine calls scale / cut → n8n alerts on every change.' },
  { key: 'bi', label: 'exec visibility', title: 'Business intelligence — the executive dashboard', ids: ['dashboard'],
    blurb: 'The decision surface leadership ran on, over the warehouse.' },
  // Public rebuilds modeled on the SAME warehouse (synthetic data) — connected, but dashed to
  // mark them as shareable rebuilds rather than production systems.
  { key: 'rebuild', label: 'public rebuilds · modeled on the warehouse', title: 'Analytics engineering & LLM tooling — public rebuilds', ids: ['nl2sql', 'dbt'], dashed: true },
];
// Detached band: only the genuinely different domain (research-lab voice AI).
export const beyondIds = ['voice'];

// ---- Career warehouse: the query engine's entries ----
// root: 'warehouse' = ran on the production warehouse I built. 'public' = synthetic rebuild.
//       'lab' = separate domain. 'meta' = summary (off graph). `label` = short graph label.
export const entries = [
  { id: 'sell', root: 'warehouse', group: 'finance', label: 'the audit', lenses: ['IB', 'BI'],
    keywords: ['reconcile', 'reconciliation', 'books', 'discrepancy', 'gap', 'audit', 'carrier', 'shipping spend', 'ledger', 'variance'],
    viz: 'reconcile',
    plan: "SELECT gap FROM carrier_spend WHERE flag = 'unmatched' → bookkeeping mis-classification",
    metric: '→ 0.5% variance', mlabel: 'six-figure discrepancy, reconciled',
    headline: 'Six-figure books reconciliation (M&A diligence)',
    narrative: "During acquisition diligence, the buyer flagged a large apparent shipping discrepancy — the ERP showed far more paid to the postal carrier than shipping labels were actually bought for. Working solo in the warehouse, I reconciled 570K+ shipping records against the SAP payment ledger and proved it was a bookkeeping mis-classification, not missing money: shipping is prepaid through two carrier 'wallets' that were both being booked under a single vendor. Counting both wallets and both payment streams, spend matched payments to ~0.5% over three years — and the correction was booked.",
    skills: ['Data reconciliation', 'Forensic analysis', 'SQL', 'ETL / API integration', 'Financial data'],
    tech: [
      "Cross-source forensic reconciliation — the ShipStation API gives ground truth on every label bought (by carrier and prepaid wallet); the SAP ledger gives what was paid and how it was booked. I joined 'spent' vs. 'paid' month-by-month and in total across both wallets and both payment streams.",
      "Root cause — one vendor code was hiding two carriers; only putting shipping ground truth next to the ERP exposed the mapping. I also traced a mid-window vendor switch that had booked some shipping as software subscriptions, and separated booking-lag timing from true variance.",
      "Result — 573,866 label records over three years reconciled to a 0.97 month-to-month correlation and ~0.5% residual variance, delivered as a color-coded proof workbook (problem/solution, monthly proof, line-item evidence) an outside diligence team could follow.",
    ],
    lineage: ['570K shipping records', 'reconciled vs ERP ledger', 'six-figure gap → bookkeeping fix'], hot: 1,
    links: [] },
  { id: 'fbt', root: 'warehouse', group: 'finance', label: 'build-vs-buy', lenses: ['IB', 'BI'],
    keywords: ['fbt', 'fulfilled-by-tiktok', 'fulfillment', 'build-vs-buy', 'build vs buy', 'shipping speed', 'rate card', 'simulation', 'natural experiment'],
    viz: 'bars',
    plan: "SELECT cost FROM fulfillment_sim(rate_card, per_sku) vs current → don't switch",
    metric: 'a firm "no"', mlabel: 'build-vs-buy, backed by data',
    headline: 'Fulfilled-by-TikTok build-vs-buy analysis',
    narrative: "TikTok pitched its Fulfilled-by-TikTok program (they warehouse & ship your inventory at a higher fee) with claims that faster shipping converts better and gets more traffic. Instead of trusting the brochure, I priced every fee and every claim against FHI's actual first-party data and recommended against blanket adoption — with a per-SKU strategy: don't convert the light-weight brushes (~95% of volume, structurally costlier under FBT), pilot the heavy tools where FBT actually saves, and make TikTok underwrite the unverifiable 'free traffic' claim. Delivered as an interactive dashboard for a non-technical decision-maker.",
    skills: ['Cost modeling', 'Causal inference (natural experiment)', 'Decision analysis', 'SQL / API data', 'Data viz'],
    tech: [
      "Per-SKU rate-card simulation — priced 11,593 fee-bearing orders individually (each against its real ShipStation weight and the exact FBT tier table), not a blended average that would hide FBT saving on heavy items but losing on light ones. FBT beat the in-house label on only ~16% of orders.",
      "Robustness — TikTok revised the rate card twice mid-analysis; I verified each change only touched 16–50 lb / multi-unit tiers, proving every FHI-relevant tier (≤5 lb) was unchanged, so the verdict survived both revisions.",
      "Causal check on the claims — a fast-vs-slow delivery-state natural experiment showed customers didn't punish slower shipping (repeat rate moved ~0.2 pts across a 3.7→6.0-day spread), and I priced the 'free traffic' claim against real ad CAC to reframe it as a concession to extract.",
    ],
    lineage: ['per-SKU rate-card simulation', 'natural experiment on shipping speed', 'recommend NO → cost avoided'], hot: 0,
    links: [] },
  { id: 'discovery', root: 'warehouse', group: 'growth', label: 'creator intel', step: '① find', lenses: ['AI', 'ML'],
    keywords: ['discovery', 'creator', 'scrape', 'scraper', 'comment', 'buy-intent', 'buy intent', 'prospect', 'outreach', 'affiliate', 'bot-block', 'machine learning', 'ml system'],
    viz: 'funnel',
    plan: "SELECT creator, buy_intent FROM scraped_comments ORDER BY buy_intent DESC → outreach list",
    metric: 'vendor-replacing', mlabel: 'creator discovery + buy-intent',
    headline: 'Creator-discovery & buy-intent pipeline',
    narrative: "To replace a third-party creator-intelligence vendor, I built a standalone pipeline that scrapes TikTok's public creator, video, and comment data — the two things no official API returns: creators outside your own shop (for cold affiliate outreach) and raw comment text scored for buy-intent. It feeds the affiliate outreach team and the decision engine below.",
    skills: ['Web scraping (anti-bot / CDP)', 'Python', 'Playwright', 'Data pipelines', 'NLP heuristics'],
    tech: [
      "Beating bot-detection (the core problem) — TikTok's comment/video endpoints are heavily defended; signed APIs and headless/headful Playwright all returned 'detecting a bot,' on datacenter and clean residential IPs alike. The breakthrough: the block is on the automated browser itself (navigator.webdriver + launch flags), not the IP — so I drive a genuine Chrome as a normal OS process and attach over the DevTools Protocol (CDP), letting TikTok's own JS sign the requests.",
      "Robust capture — read response bodies via raw CDP (Playwright returns empty for the signed endpoints); paginate comments by scrolling the last one into view and expanding reply threads (the naive method silently capped at ~40); a fresh browser context per video so one bad video can't wedge a run (verified 250 comments in ~86s).",
      "Explainable scoring & compliance — buy-intent is a transparent regex lexicon (high/med/low label + category, auditable by design — not a black box); public data only, polite pacing, and an opt-out path that deletes stored data and blocks future scraping.",
    ],
    lineage: ['drive real Chrome over CDP (beat bot-detection)', 'capture comments + replies', 'buy-intent lexicon → ranked prospects'], hot: 1,
    links: [] },
  { id: 'engine', root: 'warehouse', group: 'growth', label: 'decision engine', lenses: ['AI', 'ML', 'IB'],
    keywords: ['engine', 'decision', 'roi', 'roas', 'campaign', 'ad spend', 'adspend', 'backtest', 'breakeven', 'prove', 'accuracy', 'right'],
    viz: 'breakeven',
    shots: [
      { src: 'assets/shots/engine-decisions.png', cap: 'Decision desk — GMV Max scale/cut verdicts, impact-ranked & self-scored (synthetic rebuild of the production engine)' },
      { src: 'assets/shots/rag-demo.png', cap: 'Also public & live — the deployed synthetic demo' },
    ],
    plan: "SELECT verdict FROM ad_campaigns WHERE realized_roas < breakeven → 'cut'  (then backtest)",
    metric: '100% OOS', mlabel: 'affiliate decision engine · shipped',
    headline: 'Affiliate ad-spend decision engine',
    narrative: "The engine that told FHI's affiliate managers what to do: which creators to send product to, and which TikTok GMV Max campaign to scale, cut, or tune — grounded in real margin, guardrailed, and causally validated. A deterministic rules layer makes every call (ROAS vs. margin breakeven; creator rank vs. eligibility); an LLM only narrates the verdict and cites the evidence. Shipped and in use (a live page + a weekly one-click report). It now closes its own loop: every recommendation is archived and later graded against what actually happened, so the engine measures whether its own advice worked — then re-ranks tomorrow's actions by dollar impact.",
    skills: ['LLM agents (LangGraph)', 'RAG (Chroma)', 'Causal inference (DiD)', 'Closed-loop self-scoring', 'Unit economics', 'Out-of-sample backtest'],
    step: '② decide',
    tech: [
      "Architecture — three live sources (a 138K-creator roster, the SQL warehouse, and scraped comment text) → a deterministic decision layer (plain SQL + pandas: campaign ROAS vs. margin breakeven → cut/tune/scale; creator rank + eligibility → sample) → a RAG layer that explains each verdict and cites its evidence. 'Code decides, the LLM narrates' — the 138K creators stay in SQL and JOIN at answer time; only comments are embedded (MiniLM → Chroma).",
      "Two validations, not one — (1) campaign decisions: an out-of-sample backtest (recompute every verdict from pre-cutoff data, measure realized outcomes after, no look-ahead) hit 100% profitable/unprofitable classification across four cutoff windows — the 'keep' side rested on few campaigns, so I lean on the robust 'stop' side. (2) creator sampling: a matched-control difference-in-differences (each seeded creator vs. comparable un-sampled creators) gave rank↔lift Spearman ≈ −0.58, ~77% of sampled creators showing positive lift.",
      "Built on evidence — the scorer was rebuilt after a backtest showed prior-GMV had ~zero forward skill (information coefficient ≈ −0.03): reframed around marginal value (efficiency, buy-intent, product affinity) with a 0-video eligibility gate (53% of 'active' creators had posted nothing). Guardrails: ordinal ranks only (never size spend), protected matched controls, epsilon-greedy exploration to de-bias the learning loop, and a drift monitor (feature PSI) that can hold a release. Whole-engine eval: 5/5.",
      "Closes its own loop (self-scoring) — the engine archives each day's recommendations and later grades them against outcomes with zero look-ahead and zero manual input: a difference-in-differences check against unchanged campaigns (as control) for whether an action actually moved the number, an adoption/direction check (was the call followed?), and a daily re-validation of its own timing claims that gates alerts on sample size. Every recommended action is ranked by estimated dollar impact per month on one common scale, so the queue is prioritized by money at stake — not noise. Reported platform ROI is treated as total-channel (it claims organic + affiliate orders too) — rank with it, never size spend from it.",
    ],
    lineage: ['SQL warehouse', 'LangGraph decision engine', 'out-of-sample dollar backtest', 'self-scoring loop'], hot: 1,
    links: [['Repo (synthetic rebuild)', 'https://github.com/cmblum2/creator-insight-assistant'], ['Live demo', 'https://creator-insight-assistant.onrender.com']] },
  { id: 'n8n', root: 'warehouse', group: 'growth', label: 'n8n alerts', step: '③ alert', lenses: ['BI', 'AI'],
    keywords: ['n8n', 'workflow', 'automation', 'alert', 'no-code', 'low-code', 'watchdog', 'slack', 'discord', 'rpa'],
    viz: 'flow-n8n',
    shots: [{ src: 'assets/shots/n8n-canvas.png', cap: 'The n8n workflow canvas — schedule → diff → alert (public repo)' }],
    plan: "ON schedule → diff(state) → IF changed → POST alert(Slack)",
    metric: 'auto-alerts', mlabel: 'no-code automation (n8n)',
    headline: 'n8n alerting automation',
    narrative: "The models are only useful if someone acts on them, so I built the alerting layer as an n8n workflow: a daily schedule fans out to four watchers — new high-intent creators in the sampling queue, campaign verdicts flipping, model drift, and the 8–14-day 'spark' window on videos — each polling the deployed engine, diffing against the last run, and alerting only when something changed.",
    skills: ['Workflow automation (n8n)', 'MLOps / monitoring', 'Change detection', 'Low-code integration'],
    tech: [
      "A daily schedule trigger → 4 conditional branches, each hitting the deployed engine's endpoints, diffing the result against a persisted snapshot, and posting a chat alert (Slack/Discord) only on change — no alert fatigue — plus a dedicated error-handler workflow.",
      "A light MLOps touch — one branch polls the deployed model's /drift health endpoint, so the same layer flags model degradation, not just business events.",
      "Secrets stay out of the flow (webhook read from an env var); the public version runs against a synthetic engine, the internal twin adds a branch relaying the live /alerts.",
    ],
    lineage: ['scheduled trigger', 'diff vs last run', 'alert on change → Slack'], hot: 1,
    links: [['Repo (n8n workflow)', 'https://github.com/cmblum2/powerbi-n8n']] },
  { id: 'dashboard', root: 'warehouse', group: 'bi', label: 'exec dash', lenses: ['BI', 'IB'],
    keywords: ['dashboard', 'exec', 'executive', 'revenue', 'chart', 'report', 'bug', 'data quality', 'channel', 'visualiz'],
    viz: 'tiles',
    shots: [
      { src: 'assets/shots/powerbi-overview.png', cap: 'Power BI rebuild · executive overview (synthetic data)' },
      { src: 'assets/shots/powerbi-media-spend.png', cap: 'Media spend' },
      { src: 'assets/shots/powerbi-customers.png', cap: 'Customers' },
      { src: 'assets/shots/powerbi-inventory.png', cap: 'Inventory' },
      { src: 'assets/shots/powerbi-creators.png', cap: 'Creators' },
      { src: 'assets/shots/powerbi-search-terms.png', cap: 'Search terms' },
      { src: 'assets/shots/powerbi-conversion.png', cap: 'Conversion' },
      { src: 'assets/shots/powerbi-cash.png', cap: 'Cash' },
      { src: 'assets/shots/powerbi-model.png', cap: 'Star-schema model + DAX' },
    ],
    plan: "SELECT revenue, margin, channel FROM exec_dashboard GROUP BY day → live view",
    metric: 'display → decision', mlabel: 'exec BI app (Next.js)',
    headline: 'Executive BI dashboard',
    narrative: "The executive BI web app FHI's CEO and operators ran on — daily revenue, margin, channel, inventory, and ad views where every panel ends in a ranked 'Actions' band (cut / fix / scale / watch) plus an alert layer (stockouts, ROAS collapse, creator decay). It reframed the dashboard from display to decision, and surfaced what the DTC-only reports missed: a major wholesale channel, and a large slice of ad spend with no measurable attribution.",
    skills: ['BI / decision dashboards', 'Next.js / React', 'Performance / caching', 'Prod deploy & auth', 'Data-quality / SQL'],
    tech: [
      "Next.js 15 (App Router) over the MSSQL warehouse, panels built only on the marts layer. A cross-channel 'Product 360' rolls one physical product across Amazon, Shopify, TikTok, SAP wholesale, inventory, and ads via the canonical SKU bridge.",
      "Performance — heavy views (a ~3.6M-row SAP scan ran ~45s cold) made instant with a two-level cache (server + browser), a global mutex so heavy queries never run concurrently, warm-on-boot + background refresh, and deadlock auto-retry.",
      "Production ops — bcrypt + signed-cookie auth with per-IP lockout, and a Windows push-to-live deploy pipeline (robocopy mirror, next build with automatic .next-prev rollback on failure, behind a Cloudflare Tunnel) at ~80s per cycle over ~400 commits.",
      "Data-quality — caught a bug where a marketplace's intraday API snapshots were fanning out as duplicate sales (inflating that channel's revenue) and rebuilt the metric from deduplicated source.",
    ],
    lineage: ['warehouse marts', 'Next.js decision dashboard + Actions bands', 'production deploy (~80s push-to-live)'], hot: 1,
    links: [['Repo (Power BI rebuild)', 'https://github.com/cmblum2/powerbi-n8n']] },
  { id: 'nl2sql', root: 'public', label: 'NL→SQL', lenses: ['AI', 'BI'],
    keywords: ['nl2sql', 'text-to-sql', 'natural language', 'ask my', 'guardrail', 'self-repair', 'streamlit', 'role-scoped', 'sql agent'],
    viz: 'flow-nl2sql',
    plan: "-- \"show Q3 revenue by channel\"  →  SELECT ... (read-only, role-scoped)",
    metric: '5 roles', mlabel: 'governed NL→SQL agent · live',
    headline: 'NL→SQL analytics agent (governed)',
    narrative: "A LangGraph agent that turns plain-English questions into governed SQL — read-only, self-repairing, with role-based access enforced in three layers (schema-scoped prompt, a guard, and per-role DuckDB views). Public rebuild on synthetic data modeled on my warehouse; live demo with five role logins (ask it to 'delete all orders' and it refuses).",
    skills: ['LLM agents (LangGraph)', 'Text-to-SQL', 'Guardrails / governance', 'Evaluation'],
    tech: [
      "LangGraph agent: NL → SQL → execute → chart, with a guardrail node (read-only SELECT only, forced LIMIT, blocks DML) and a self-repair loop (catch SQL error → feed it back → retry).",
      "Role-based access in three layers: a schema-scoped prompt, a guard that rejects out-of-scope columns, and per-role DuckDB views as a physical backstop (hidden columns literally absent).",
      "DuckDB engine, Streamlit UI, and an evaluation harness — on synthetic data modeled on my real warehouse schema.",
    ],
    lineage: ['plain-English question', 'LangGraph → guardrailed read-only SQL', 'chart + answer, or a refusal'], hot: 1,
    links: [['Repo', 'https://github.com/cmblum2/nl2sql-agent'], ['Live demo', 'https://ask-your-warehouse.streamlit.app']] },
  { id: 'dbt', root: 'public', label: 'dbt', lenses: ['BI', 'AI'],
    keywords: ['dbt', 'bigquery', 'analytics engineering', 'staging', 'marts', 'lineage', 'transform', 'ci', 'elt', 'data test'],
    viz: 'dag',
    shots: [{ src: 'assets/shots/dbt-lineage.png', cap: 'dbt docs — the model lineage DAG (synthetic data · public repo)' }],
    plan: "dbt build → 3 seeds · 6 models · 22/22 tests passed (CI on every push)",
    metric: '22/22 tests', mlabel: 'dbt + BigQuery, CI-tested',
    headline: 'dbt + BigQuery analytics warehouse',
    narrative: "A retail warehouse modeled in dbt on BigQuery (raw → staging → marts) with data tests, lineage docs, and GitHub Actions CI running the full build + 22 tests on every push. Public rebuild on synthetic data — the named-stack, reproducible version of my production modeling.",
    skills: ['Analytics engineering (dbt)', 'BigQuery', 'Data testing', 'CI/CD'],
    tech: [
      "dbt on BigQuery: raw → staging (clean and type) → marts (fact_daily_revenue, dim_product with unit margin, channel rollups).",
      "Data tests (not_null, unique, relationships, accepted_values) plus auto-generated lineage docs.",
      "GitHub Actions CI runs the full dbt build and tests in an isolated dataset on every push (service-account auth).",
    ],
    lineage: ['raw seeds', 'staging → marts (dbt)', '22 data tests, green in CI'], hot: 1,
    links: [['Repo', 'https://github.com/cmblum2/retail-analytics-dbt']] },
  { id: 'voice', root: 'lab', rootLabel: 'research lab', label: 'voice AI', lenses: ['AI', 'ML'],
    keywords: ['voice', 'realtime', 'audio', 'hands-free', 'speech', 'dictation', 'assistant', 'openai', 'stemy'],
    viz: 'flow-voice',
    plan: "SELECT story FROM research_lab WHERE domain = 'voice-ai' → 1 row",
    metric: 'NIH R01', mlabel: 'People and Robots Lab × Kamp Lab · UW–Madison · ongoing',
    headline: 'Voice-first lab assistant (SteMy)',
    narrative: "SteMy is a hands-free voice AI lab partner for stem-cell researchers. Turning stem cells into heart cells is notoriously irreproducible batch-to-batch — and researchers are hands-busy at the hood during time-sensitive windows, with dozens of variables to track. I build and lead the voice-interaction layer that lets them capture and recall the right experimental variable at the right moment, hands-free. A separate, ongoing UW–Madison research engagement with the People and Robots Lab (Prof. Bilge Mutlu) × the Kamp Lab (Dr. Timothy Kamp); part of an active NIH R01 that scored highly — funding anticipated.",
    skills: ['Voice AI (OpenAI Realtime)', 'Function-calling', 'Human-in-the-loop safety', 'Real-time systems', 'Research engineering'],
    tech: [
      "Domain-tuned voice UX — protocol- and study-day-aware (it prompts for the variables that matter at that differentiation stage), with lab-reality speech: biology-vocabulary biasing, number normalization, anaphora memory ('that replicate'), hands-free wake-phrase + barge-in, and confidence-gated auto-execute with a clarification fallback.",
      "Architecture — full-stack (React 18 + Vite / Python + FastAPI + SQLite); real-time voice via OpenAI's Realtime API over a persistent WebRTC session (~600–900ms), with server-mediated tools: ephemeral session tokens, a per-page tool catalog, and one executor enforcing auth + telemetry. Migrated from a ~1.8–3s turn-based pipeline without a rewrite; the hard state lives in the backend (slot-filling, a navigate_to tool) so the LLM has one narrow job per turn.",
      "Safety & shipping — a spoken confirmation gate before any action that changes an experiment record; shipped in phases behind a runtime feature flag (roll back from the browser, no redeploy), covered by Vitest + HTTP smoke-test suites that caught a stale-session bug pre-release.",
      "Scope & funding — I build and lead the voice/tools layer; teammates build the agent and the reproducibility 'brain.' Co-author on the methods paper; part of an active NIH R01 that scored highly (funding anticipated).",
    ],
    lineage: ['OpenAI Realtime (full-duplex speech)', 'voice → backend function calls', 'spoken confirmation before any action'], hot: 1,
    links: [] },
  { id: 'warehouse', root: 'warehouse', label: 'warehouse', lenses: ['BI', 'IB'],
    keywords: ['warehouse', 'data', 'pipeline', 'erp', 'source', 'database', 'backbone', 'infrastructure', 'ingestion', 'etl', 'from scratch'],
    viz: 'fanin',
    plan: "SELECT * FROM (shopify, amazon_seller/vendor/ads, tiktok_shop/ads, meta, google_ads/ga4/gsc/gmc, sap, shipstation, attentive, euka) → conformed_schema",
    metric: '15+ systems → 1', mlabel: 'unified warehouse, built from scratch',
    headline: 'Multi-source data warehouse — built from scratch',
    narrative: "Designed and built FHI Heat's SQL warehouse from zero — a dbt-style raw → staging → marts model (hundreds of tables/views) unifying ~15 source systems across the US & EU via nightly Python ETL: every commerce, ad, search, ERP, fulfillment, and marketing platform the company runs on. The single source of truth every downstream tool queries.",
    skills: ['Data engineering', 'ETL / ELT', 'Dimensional modeling', 'Data integration', 'SQL', 'Python'],
    tech: [
      "Sources (~15, US & EU) — commerce: Shopify, Amazon (Seller + Vendor Central), TikTok Shop. Ads: Amazon, TikTok, Meta, Google. Search & analytics: Google Analytics (GA4), Search Console, Merchant Center. Plus SAP B1 (ERP), ShipStation, Attentive, and Euka — each via its own API.",
      "Scale & schema — a dbt-style raw → staging → marts model: ~380 tables / ~120 views across 6 schemas, tens of millions of rows (SAP invoice lines and Attentive events alone run into the millions), conformed onto shared dimensions via a cross-marketplace SKU bridge that resolves one physical product across every channel; USD/EUR normalization; nightly Python ETL.",
      "Reliability & reconciliation — incremental idempotent upserts, schema-drift handling, snapshot de-duplication, and data-quality checks; cross-source reconciliation (ad spend across platforms vs. the SAP ledger, Amazon Seller vs. Vendor, GA4 vs. orders) into one revenue-and-margin view.",
    ],
    lineage: ['Shopify · Amazon · TikTok · Meta · Google · SAP · ShipStation · Attentive · Euka', 'nightly Python ETL · raw→staging→marts', 'one conformed SQL schema'], hot: 2,
    links: [] },
  { id: 'stack', root: 'meta', label: 'stack', lenses: ['AI', 'ML', 'BI', 'IB'],
    keywords: ['stack', 'tool', 'tech', 'skill', 'langgraph', 'power bi', 'powerbi', 'python', 'languages'],
    plan: "SELECT tool, proof FROM stack WHERE shipped = true → each maps to a repo",
    metric: 'each → a repo', mlabel: 'tools, honestly earned',
    headline: 'The toolset — every tool tied to a shipped project.',
    narrative: 'AI / LLM: LangGraph agents, RAG (Chroma), RAGAS evaluation, Claude & OpenAI. Data: dbt + BigQuery, Python, SQL, Docker, GitHub Actions CI. Automation/BI: n8n, Power BI (star schema + DAX), Next.js dashboards. ML/Rigor: web scraping, buy-intent scoring, causal inference, out-of-sample backtesting, guardrails. Every item points to a project above, not a course checklist.',
    lineage: ['raw skills', 'staging (projects)', 'marts (shipped + evaluated)'], hot: 2,
    links: [['GitHub', 'https://github.com/cmblum2']] },
  { id: 'deploy', root: 'meta', label: 'deploy', lenses: ['AI', 'BI'],
    keywords: ['deploy', 'live', 'running', 'host', 'hosted', 'url', 'demo', 'production', 'uptime'],
    plan: "SELECT name, state FROM deployments WHERE state != 'down' → live",
    metric: '3 public apps', mlabel: 'deployed + reachable',
    headline: 'Live deployments',
    narrative: "Three public apps you can hit right now — the NL→SQL agent (Streamlit), the decision-engine rebuild (Render), and the dbt warehouse with green CI — plus this site. The status bar pings them every 30 minutes; free-tier demos nap when idle and wake on first click.",
    skills: ['Deployment', 'CI/CD', 'GitHub Pages · Streamlit · Render'],
    lineage: ['Streamlit · NL→SQL agent', 'Render · decision-engine rebuild', 'GitHub Actions · dbt CI'], hot: -1,
    links: [['NL→SQL', 'https://ask-your-warehouse.streamlit.app'], ['Decision engine', 'https://creator-insight-assistant.onrender.com']] },
];

export const DEFAULT_ENTRY = 'warehouse';

// ---- Fallback (scroll) content, carried from v1 ----
export const profile = { name: 'Camryn Blum', kicker: 'CS + Data Science · UW–Madison' };

export const caseStudies = [
  { id: 'engine', claim: 'The AI engine\'s calls, validated out of sample', value: '100% OOS', lenses: ['AI', 'ML', 'IB'],
    method: 'Recompute every campaign verdict from data before a cutoff, then measure what actually happened after — same decision function as the live engine, no look-ahead.',
    result: '100% profitable/unprofitable accuracy across four cutoff windows — every campaign it flagged to stop was genuinely below breakeven, and the ones it called healthy were solidly profitable.',
    caveat: 'The "keep" side rested on few campaigns in-window — I present it as directional and lean on the robust "stop" side. Downstream adoption was above my intern access.' },
  { id: 'audit', claim: 'A six-figure books discrepancy — reconciled to 0.5%', value: '0.5% var', lenses: ['IB', 'BI'],
    method: 'Pulled 570K+ shipping records into the warehouse I built and reconciled them line-by-line against the ERP payment ledger.',
    result: 'Proved it was a bookkeeping mis-classification, not missing money: two prepaid carrier wallets booked under one vendor. Counting both, spend matched payments to within ~0.5%; the correction was booked.',
    caveat: 'I built the warehouse and did the reconciliation myself; some downstream financials were confidential above my intern access.' },
];

export const stack = [
  { group: 'AI / LLM', items: ['LangGraph agents', 'RAG · Chroma', 'RAGAS eval', 'Claude / OpenAI'] },
  { group: 'Data / Eng', items: ['multi-source ETL', 'dimensional modeling', 'dbt · BigQuery', 'Python · SQL'] },
  { group: 'ML / Rigor', items: ['buy-intent scoring', 'causal inference', 'OOS backtesting', 'guardrails · eval'] },
  { group: 'BI / Automation', items: ['Power BI · DAX', 'Next.js dashboards', 'n8n workflows', 'star-schema modeling'] },
];

export const links = {
  github: 'https://github.com/cmblum2', linkedin: '#', resume: '#', email: 'camrynblum@gmail.com',
};
